version: '3.8'
services:
  mealplanner:
    build: ./src/Agents/MealPlannerAgent
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  orchestrator:
    build: ./src/Orchestrator
    ports:
      - "5000:80"
  model-runner:
    image: ghcr.io/some/model-runner:latest
    ports:
      - "8000:8000"
  ui:
    build: ./src/UI
    ports:
      - "3000:80"
