services:
  budget:
    build: 
      context: ./src
      dockerfile: ./Agents/BudgetAgent/Dockerfile
    ports:
      - "5001:80"
    models:
      - llm
  inventory:
    build: 
      context: ./src
      dockerfile: ./Agents/InventoryAgent/Dockerfile
    ports:
      - "5002:80"
    models:
      - llm
  mealplanner:
    build: 
      context: ./src
      dockerfile: ./Agents/MealPlannerAgent/Dockerfile
    ports:
      - "5003:80"
    models:
      - llm
  
  ui:
    build: ./src/UI
    ports:
      - "3000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DataProtection__KeyPath=/keys
    volumes:
      - ./data/ui-keys:/keys
  shopper:
    build: 
      context: ./src
      dockerfile: ./Agents/ShopperAgent/Dockerfile
    ports:
      - "5004:80"
    models:
      - llm
models:
  llm:
    model: ai/smollm2
    # model: ai/gemma3
