version: '3.8'
services:
  budget:
    build: ./src/Agents/BudgetAgent
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    models:
      - llm
  inventory:
    build: ./src/Agents/InventoryAgent
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    models:
      - llm
  mealplanner:
    build: ./src/Agents/MealPlannerAgent
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    models:
      - llm
  orchestrator:
    build: ./src/Orchestrator
    ports:
      - "5000:80"
  ui:
    build: ./src/UI
    ports:
      - "3000:80"
  shopper:
    build: ./src/Agents/ShopperAgent
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    models:
      - llm
models:
  llm:
    model: ai/smollm2
